In [31]:
import pandas as pd

In [32]:
## Importing CSV file of all 311 service requests over tree overgrowth since 2020.

df = pd.read_csv("311_Service_Requests_from_2020_to_Present_20260418.csv", low_memory=False)
df

,Unique Key,Created Date,Closed Date,Agency,Agency Name,Problem (formerly Complaint Type),Problem Detail (formerly Descriptor),Additional Details,Location Type,Incident Zip,...,Vehicle Type,Taxi Company Borough,Taxi Pick Up Location,Bridge Highway Name,Bridge Highway Direction,Road Ramp,Bridge Highway Segment,Latitude,Longitude,Location
0,68686983,04/16/2026 10:23:21 PM,NaN,DPR,Department of Parks and Recreation,Overgrown Tree/Branches,Dead Branches in Tree,NaN,Street,11229.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.612413,-73.948989,POINT (-73.94898883473 40.612412817701)
1,68692873,04/16/2026 10:13:05 PM,NaN,DPR,Department of Parks and Recreation,Overgrown Tree/Branches,Blocking Street,NaN,Street,11360.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.773689,-73.790222,POINT (-73.790222247377 40.773688655549)
2,68691466,04/16/2026 09:00:36 PM,NaN,DPR,Department of Parks and Recreation,Overgrown Tree/Branches,Hitting Building,NaN,Street,11232.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.647612,-73.999384,POINT (-73.999383780931 40.64761232864)
3,68685506,04/16/2026 08:13:49 PM,NaN,DPR,Department of Parks and Recreation,Overgrown Tree/Branches,Dead Branches in Tree,NaN,Street,11214.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.613923,-74.001484,POINT (-74.001483942265 40.613922784564)
4,68694512,04/16/2026 07:44:59 PM,NaN,DPR,Department of Parks and Recreation,Overgrown Tree/Branches,Hitting Power Lines,Power Lines,Street,10308.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.537908,-74.146592,POINT (-74.146592149775 40.537907951065)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117324,45289460,01/01/2020 02:01:49 PM,01/31/2020 02:15:47 PM,DPR,Department of Parks and Recreation,Overgrown Tree/Branches,Hitting Power/Phone Lines,Power Lines,Street/Curbside,10461.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.835496,-73.829519,POINT (-73.829519028237 40.835496198678)
117325,45287365,01/01/2020 01:04:41 PM,05/26/2020 10:30:40 AM,DPR,Department of Parks and Recreation,Overgrown Tree/Branches,Hitting Building,NaN,Street/Curbside,10031.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.827904,-73.949893,POINT (-73.949893194848 40.827904157923)
117326,45285876,01/01/2020 10:00:08 AM,01/07/2020 11:14:31 AM,DPR,Department of Parks and Recreation,Overgrown Tree/Branches,Dead Branches in Tree,NaN,Street,11229.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.594081,-73.951639,POINT (-73.951638574453 40.594081464551)
117327,45287411,01/01/2020 09:58:10 AM,01/21/2020 12:27:36 PM,DPR,Department of Parks and Recreation,Overgrown Tree/Branches,Hitting Building,NaN,Street/Curbside,11215.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.673039,-73.971802,POINT (-73.971801735372 40.673039257846)
117328,45286498,01/01/2020 08:06:46 AM,01/07/2020 12:09:01 PM,DPR,Department of Parks and Recreation,Overgrown Tree/Branches,Dead Branches in Tree,NaN,Street,11238.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
## Filtering out entries prior to 2023 for time relevance.

df['Created Date'] = pd.to_datetime(df['Created Date'], errors='coerce')
dfRecent = df[df['Created Date'] >= pd.Timestamp('2023-01-01 00:00:00')]
dfRecent

/var/folders/z2/y57stfxx4ydftjrt24bjsy1w0000gn/T/ipykernel_67739/296982722.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Created Date'] = pd.to_datetime(df['Created Date'], errors='coerce')

,Unique Key,Created Date,Closed Date,Agency,Agency Name,Problem (formerly Complaint Type),Problem Detail (formerly Descriptor),Additional Details,Location Type,Incident Zip,...,Vehicle Type,Taxi Company Borough,Taxi Pick Up Location,Bridge Highway Name,Bridge Highway Direction,Road Ramp,Bridge Highway Segment,Latitude,Longitude,Location
0,68686983,2026-04-16 22:23:21,NaN,DPR,Department of Parks and Recreation,Overgrown Tree/Branches,Dead Branches in Tree,NaN,Street,11229.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.612413,-73.948989,POINT (-73.94898883473 40.612412817701)
1,68692873,2026-04-16 22:13:05,NaN,DPR,Department of Parks and Recreation,Overgrown Tree/Branches,Blocking Street,NaN,Street,11360.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.773689,-73.790222,POINT (-73.790222247377 40.773688655549)
2,68691466,2026-04-16 21:00:36,NaN,DPR,Department of Parks and Recreation,Overgrown Tree/Branches,Hitting Building,NaN,Street,11232.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.647612,-73.999384,POINT (-73.999383780931 40.64761232864)
3,68685506,2026-04-16 20:13:49,NaN,DPR,Department of Parks and Recreation,Overgrown Tree/Branches,Dead Branches in Tree,NaN,Street,11214.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.613923,-74.001484,POINT (-74.001483942265 40.613922784564)
4,68694512,2026-04-16 19:44:59,NaN,DPR,Department of Parks and Recreation,Overgrown Tree/Branches,Hitting Power Lines,Power Lines,Street,10308.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.537908,-74.146592,POINT (-74.146592149775 40.537907951065)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64356,56419290,2023-01-01 19:59:17,11/12/2024 05:04:21 PM,DPR,Department of Parks and Recreation,Overgrown Tree/Branches,Dead Branches in Tree,NaN,Street,11207.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.684737,-73.908002,POINT (-73.908002421906 40.684737100252)
64357,56416779,2023-01-01 18:41:23,NaN,DPR,Department of Parks and Recreation,Overgrown Tree/Branches,Hitting Power Lines,Power Lines,Street,11228.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.622705,-74.013047,POINT (-74.013047442089 40.622705389141)
64358,56419485,2023-01-01 14:44:39,01/03/2023 10:12:47 AM,DPR,Department of Parks and Recreation,Overgrown Tree/Branches,Hitting Building,NaN,Street,10314.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.608719,-74.137225,POINT (-74.13722520411 40.608719091559)
64359,56417803,2023-01-01 11:41:04,11/12/2024 05:04:19 PM,DPR,Department of Parks and Recreation,Overgrown Tree/Branches,Hitting Building,NaN,Street,11233.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.682328,-73.912610,POINT (-73.912609966558 40.682328035881)
64360,56414628,2023-01-01 10:55:54,11/12/2024 05:04:18 PM,DPR,Department of Parks and Recreation,Overgrown Tree/Branches,Dead Branches in Tree,NaN,Street,11435.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.695509,-73.810602,POINT (-73.810601750594 40.695509279403)

In [35]:
## Examining all possible zip codes.

zip_codes_all = dfRecent['Incident Zip'].unique()
print(zip_codes_all)

[11229. 11360. 11232. 11214. 10308. 11355. 11420. 10027. 11412. 11223.
 10469. 11211. 10465. 11208. 11218. 10028. 11361. 11365. 11368. 10312.
 11228. 10304. 11426. 11428. 11234. 11422. 11411. 11106. 10003. 11206.
 11423. 11362. 11207. 11226. 11205. 11204. 10473. 11370. 10467. 10306.
 11385. 11377. 11691. 11366. 11238. 11004. 11221. 11215. 11421. 10314.
 11216. 11434. 11203. 11375. 11374. 10031. 11416. 11379. 11433. 11210.
 11220. 11369. 11427. 11230. 11233. 11213. 11212. 11236. 11413. 11357.
 10453. 11364. 11222. 11356. 11225. 11235. 10470. 10307. 10309. 11429.
 11217. 10305. 10472. 10464. 11102. 11105.    nan 11418. 10466. 11237.
 10471. 10022. 10009. 10065. 10461. 11103. 11209. 11435. 10458. 11373.
 11417. 10030. 11354. 11358. 10026. 10034. 11432. 10463. 10459. 11101.
 11419. 10035. 10013. 10301. 11001. 11693. 10303. 11231. 10016. 10021.
 11436. 11219. 10302. 10029. 11694. 11415. 10456. 10002. 10462. 10310.
 11378. 11224. 10019. 11414. 11201. 11372. 11367. 11363. 10460. 10451.
 11249. 10025. 10011. 10023. 10039. 10024. 10457. 11692. 11104. 10475.
 10040. 10017. 10012. 10014. 10454. 10455. 10004. 10036. 10128. 10075.
 10032. 11040. 10033. 10006. 10001. 10468. 10010. 10007. 10452. 10474.
 10069. 11239. 10038. 10281. 10037. 10018. 10162. 11359. 10280. 11697.
 11109. 10282.]

In [36]:
## Counting reports per zip code.

zip_counts = (
    dfRecent['Incident Zip']
    .value_counts(dropna=False)
    .reset_index()
)

zip_counts.columns = ['Incident Zip', 'Count']
zip_counts.head(15)

    Incident Zip  Count
0        11234.0   2332
1        10312.0   1600
2        10314.0   1435
3        10306.0   1372
4        11385.0   1199
5        11236.0   1112
6        11203.0   1075
7        11230.0   1057
8        11229.0   1043
9        11209.0   1030
10       11210.0    993
11       11434.0    988
12       11420.0    985
13       11223.0    898
14       11358.0    896

In [37]:
## Returning dataframe as a CSV to visualize in Datawrapper

zip_counts.to_csv("zip_counts.csv", index=False)